// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'book': string;
  'bookHeader': string;
  'bookSelectedContainer': string;
  'bookTitle': string;
  'previews': string;
  'selectAllInput': string;
  'selectAllInputContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
