// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details': string;
  'path': string;
  'quality': string;
  'reason': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
